//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace MapLink.RoteValuesCalculator.br.com.maplink.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddressFinderSoap", Namespace="http://webservices.maplink2.com.br")]
    public partial class AddressFinder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback findPOIOperationCompleted;
        
        private System.Threading.SendOrPostCallback findAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback findRoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback findDistrictOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXYOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRoadXYOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXYRadiusWithMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback findCityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AddressFinder() {
            this.Url = global::MapLink.RoteValuesCalculator.Properties.Settings.Default.MapLink_RoteValuesCalculator_br_com_maplink_services_AddressFinder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event findPOICompletedEventHandler findPOICompleted;
        
        /// <remarks/>
        public event findAddressCompletedEventHandler findAddressCompleted;
        
        /// <remarks/>
        public event findRoadCompletedEventHandler findRoadCompleted;
        
        /// <remarks/>
        public event findDistrictCompletedEventHandler findDistrictCompleted;
        
        /// <remarks/>
        public event getAddressCompletedEventHandler getAddressCompleted;
        
        /// <remarks/>
        public event getXYCompletedEventHandler getXYCompleted;
        
        /// <remarks/>
        public event getRoadXYCompletedEventHandler getRoadXYCompleted;
        
        /// <remarks/>
        public event getXYRadiusWithMapCompletedEventHandler getXYRadiusWithMapCompleted;
        
        /// <remarks/>
        public event findCityCompletedEventHandler findCityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/findPOI", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public POIInfo findPOI(string name, City city, ResultRange resultRange, string token) {
            object[] results = this.Invoke("findPOI", new object[] {
                        name,
                        city,
                        resultRange,
                        token});
            return ((POIInfo)(results[0]));
        }
        
        /// <remarks/>
        public void findPOIAsync(string name, City city, ResultRange resultRange, string token) {
            this.findPOIAsync(name, city, resultRange, token, null);
        }
        
        /// <remarks/>
        public void findPOIAsync(string name, City city, ResultRange resultRange, string token, object userState) {
            if ((this.findPOIOperationCompleted == null)) {
                this.findPOIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindPOIOperationCompleted);
            }
            this.InvokeAsync("findPOI", new object[] {
                        name,
                        city,
                        resultRange,
                        token}, this.findPOIOperationCompleted, userState);
        }
        
        private void OnfindPOIOperationCompleted(object arg) {
            if ((this.findPOICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findPOICompleted(this, new findPOICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/findAddress", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddressInfo findAddress(Address address, AddressOptions ao, string token) {
            object[] results = this.Invoke("findAddress", new object[] {
                        address,
                        ao,
                        token});
            return ((AddressInfo)(results[0]));
        }
        
        /// <remarks/>
        public void findAddressAsync(Address address, AddressOptions ao, string token) {
            this.findAddressAsync(address, ao, token, null);
        }
        
        /// <remarks/>
        public void findAddressAsync(Address address, AddressOptions ao, string token, object userState) {
            if ((this.findAddressOperationCompleted == null)) {
                this.findAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindAddressOperationCompleted);
            }
            this.InvokeAsync("findAddress", new object[] {
                        address,
                        ao,
                        token}, this.findAddressOperationCompleted, userState);
        }
        
        private void OnfindAddressOperationCompleted(object arg) {
            if ((this.findAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findAddressCompleted(this, new findAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/findRoad", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RoadInfo findRoad(Road road, string token) {
            object[] results = this.Invoke("findRoad", new object[] {
                        road,
                        token});
            return ((RoadInfo)(results[0]));
        }
        
        /// <remarks/>
        public void findRoadAsync(Road road, string token) {
            this.findRoadAsync(road, token, null);
        }
        
        /// <remarks/>
        public void findRoadAsync(Road road, string token, object userState) {
            if ((this.findRoadOperationCompleted == null)) {
                this.findRoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindRoadOperationCompleted);
            }
            this.InvokeAsync("findRoad", new object[] {
                        road,
                        token}, this.findRoadOperationCompleted, userState);
        }
        
        private void OnfindRoadOperationCompleted(object arg) {
            if ((this.findRoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findRoadCompleted(this, new findRoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/findDistrict", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DistrictInfo findDistrict(District district, ResultRange rr, string token) {
            object[] results = this.Invoke("findDistrict", new object[] {
                        district,
                        rr,
                        token});
            return ((DistrictInfo)(results[0]));
        }
        
        /// <remarks/>
        public void findDistrictAsync(District district, ResultRange rr, string token) {
            this.findDistrictAsync(district, rr, token, null);
        }
        
        /// <remarks/>
        public void findDistrictAsync(District district, ResultRange rr, string token, object userState) {
            if ((this.findDistrictOperationCompleted == null)) {
                this.findDistrictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindDistrictOperationCompleted);
            }
            this.InvokeAsync("findDistrict", new object[] {
                        district,
                        rr,
                        token}, this.findDistrictOperationCompleted, userState);
        }
        
        private void OnfindDistrictOperationCompleted(object arg) {
            if ((this.findDistrictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findDistrictCompleted(this, new findDistrictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getAddress", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddressLocation getAddress(Point point, string token, double tolerance) {
            object[] results = this.Invoke("getAddress", new object[] {
                        point,
                        token,
                        tolerance});
            return ((AddressLocation)(results[0]));
        }
        
        /// <remarks/>
        public void getAddressAsync(Point point, string token, double tolerance) {
            this.getAddressAsync(point, token, tolerance, null);
        }
        
        /// <remarks/>
        public void getAddressAsync(Point point, string token, double tolerance, object userState) {
            if ((this.getAddressOperationCompleted == null)) {
                this.getAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAddressOperationCompleted);
            }
            this.InvokeAsync("getAddress", new object[] {
                        point,
                        token,
                        tolerance}, this.getAddressOperationCompleted, userState);
        }
        
        private void OngetAddressOperationCompleted(object arg) {
            if ((this.getAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAddressCompleted(this, new getAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getXY", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Point getXY(Address address, string token) {
            object[] results = this.Invoke("getXY", new object[] {
                        address,
                        token});
            return ((Point)(results[0]));
        }
        
        /// <remarks/>
        public void getXYAsync(Address address, string token) {
            this.getXYAsync(address, token, null);
        }
        
        /// <remarks/>
        public void getXYAsync(Address address, string token, object userState) {
            if ((this.getXYOperationCompleted == null)) {
                this.getXYOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXYOperationCompleted);
            }
            this.InvokeAsync("getXY", new object[] {
                        address,
                        token}, this.getXYOperationCompleted, userState);
        }
        
        private void OngetXYOperationCompleted(object arg) {
            if ((this.getXYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXYCompleted(this, new getXYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getRoadXY", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Point getRoadXY(Road road, string token) {
            object[] results = this.Invoke("getRoadXY", new object[] {
                        road,
                        token});
            return ((Point)(results[0]));
        }
        
        /// <remarks/>
        public void getRoadXYAsync(Road road, string token) {
            this.getRoadXYAsync(road, token, null);
        }
        
        /// <remarks/>
        public void getRoadXYAsync(Road road, string token, object userState) {
            if ((this.getRoadXYOperationCompleted == null)) {
                this.getRoadXYOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRoadXYOperationCompleted);
            }
            this.InvokeAsync("getRoadXY", new object[] {
                        road,
                        token}, this.getRoadXYOperationCompleted, userState);
        }
        
        private void OngetRoadXYOperationCompleted(object arg) {
            if ((this.getRoadXYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRoadXYCompleted(this, new getRoadXYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/getXYRadiusWithMap", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MapInfo getXYRadiusWithMap(Address address, MapOptions mo, int radius, string token) {
            object[] results = this.Invoke("getXYRadiusWithMap", new object[] {
                        address,
                        mo,
                        radius,
                        token});
            return ((MapInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getXYRadiusWithMapAsync(Address address, MapOptions mo, int radius, string token) {
            this.getXYRadiusWithMapAsync(address, mo, radius, token, null);
        }
        
        /// <remarks/>
        public void getXYRadiusWithMapAsync(Address address, MapOptions mo, int radius, string token, object userState) {
            if ((this.getXYRadiusWithMapOperationCompleted == null)) {
                this.getXYRadiusWithMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXYRadiusWithMapOperationCompleted);
            }
            this.InvokeAsync("getXYRadiusWithMap", new object[] {
                        address,
                        mo,
                        radius,
                        token}, this.getXYRadiusWithMapOperationCompleted, userState);
        }
        
        private void OngetXYRadiusWithMapOperationCompleted(object arg) {
            if ((this.getXYRadiusWithMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXYRadiusWithMapCompleted(this, new getXYRadiusWithMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.maplink2.com.br/findCity", RequestNamespace="http://webservices.maplink2.com.br", ResponseNamespace="http://webservices.maplink2.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CityLocationInfo findCity(City cidade, AddressOptions ao, string token) {
            object[] results = this.Invoke("findCity", new object[] {
                        cidade,
                        ao,
                        token});
            return ((CityLocationInfo)(results[0]));
        }
        
        /// <remarks/>
        public void findCityAsync(City cidade, AddressOptions ao, string token) {
            this.findCityAsync(cidade, ao, token, null);
        }
        
        /// <remarks/>
        public void findCityAsync(City cidade, AddressOptions ao, string token, object userState) {
            if ((this.findCityOperationCompleted == null)) {
                this.findCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindCityOperationCompleted);
            }
            this.InvokeAsync("findCity", new object[] {
                        cidade,
                        ao,
                        token}, this.findCityOperationCompleted, userState);
        }
        
        private void OnfindCityOperationCompleted(object arg) {
            if ((this.findCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findCityCompleted(this, new findCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class City {
        
        private string nameField;
        
        private string stateField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class CityLocation {
        
        private City cityField;
        
        private Point pointField;
        
        private bool carAccessField;
        
        private string zipRangeStartField;
        
        private string zipRangeEndField;
        
        private bool capitalField;
        
        private bool addressesAvailableField;
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public bool carAccess {
            get {
                return this.carAccessField;
            }
            set {
                this.carAccessField = value;
            }
        }
        
        /// <remarks/>
        public string zipRangeStart {
            get {
                return this.zipRangeStartField;
            }
            set {
                this.zipRangeStartField = value;
            }
        }
        
        /// <remarks/>
        public string zipRangeEnd {
            get {
                return this.zipRangeEndField;
            }
            set {
                this.zipRangeEndField = value;
            }
        }
        
        /// <remarks/>
        public bool capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
            }
        }
        
        /// <remarks/>
        public bool addressesAvailable {
            get {
                return this.addressesAvailableField;
            }
            set {
                this.addressesAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Point {
        
        private double xField;
        
        private double yField;
        
        /// <remarks/>
        public double x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public double y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class CityLocationInfo {
        
        private int recordCountField;
        
        private int pageCountField;
        
        private CityLocation[] cityLocationField;
        
        /// <remarks/>
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CityLocation[] cityLocation {
            get {
                return this.cityLocationField;
            }
            set {
                this.cityLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Extent {
        
        private double xMinField;
        
        private double yMinField;
        
        private double xMaxField;
        
        private double yMaxField;
        
        /// <remarks/>
        public double XMin {
            get {
                return this.xMinField;
            }
            set {
                this.xMinField = value;
            }
        }
        
        /// <remarks/>
        public double YMin {
            get {
                return this.yMinField;
            }
            set {
                this.yMinField = value;
            }
        }
        
        /// <remarks/>
        public double XMax {
            get {
                return this.xMaxField;
            }
            set {
                this.xMaxField = value;
            }
        }
        
        /// <remarks/>
        public double YMax {
            get {
                return this.yMaxField;
            }
            set {
                this.yMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapInfo {
        
        private string urlField;
        
        private Extent extentField;
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public Extent extent {
            get {
                return this.extentField;
            }
            set {
                this.extentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapSize {
        
        private int widthField;
        
        private int heightField;
        
        /// <remarks/>
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class MapOptions {
        
        private bool scaleBarField;
        
        private MapSize mapSizeField;
        
        /// <remarks/>
        public bool scaleBar {
            get {
                return this.scaleBarField;
            }
            set {
                this.scaleBarField = value;
            }
        }
        
        /// <remarks/>
        public MapSize mapSize {
            get {
                return this.mapSizeField;
            }
            set {
                this.mapSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class DistrictLocation {
        
        private District districtField;
        
        private Point pointField;
        
        /// <remarks/>
        public District district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class District {
        
        private City cityField;
        
        private string nameField;
        
        private string zoneField;
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class DistrictInfo {
        
        private int recordCountField;
        
        private int pageCountField;
        
        private DistrictLocation[] districtLocationField;
        
        /// <remarks/>
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DistrictLocation[] districtLocation {
            get {
                return this.districtLocationField;
            }
            set {
                this.districtLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RoadDetail {
        
        private string alterNameField;
        
        private string complementField;
        
        private string districtField;
        
        private string directionField;
        
        /// <remarks/>
        public string alterName {
            get {
                return this.alterNameField;
            }
            set {
                this.alterNameField = value;
            }
        }
        
        /// <remarks/>
        public string complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
            }
        }
        
        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RoadLocation {
        
        private Road roadField;
        
        private RoadDetail roadDetailField;
        
        /// <remarks/>
        public Road road {
            get {
                return this.roadField;
            }
            set {
                this.roadField = value;
            }
        }
        
        /// <remarks/>
        public RoadDetail roadDetail {
            get {
                return this.roadDetailField;
            }
            set {
                this.roadDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Road {
        
        private string nameField;
        
        private string roadNumberField;
        
        private string zipField;
        
        private City cityField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string roadNumber {
            get {
                return this.roadNumberField;
            }
            set {
                this.roadNumberField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class RoadInfo {
        
        private int recordCountField;
        
        private int pageCountField;
        
        private RoadLocation[] roadLocationField;
        
        /// <remarks/>
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RoadLocation[] roadLocation {
            get {
                return this.roadLocationField;
            }
            set {
                this.roadLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class AddressLocation {
        
        private string keyField;
        
        private Address addressField;
        
        private string zipLField;
        
        private string zipRField;
        
        private bool carAccessField;
        
        private string dataSourceField;
        
        private Point pointField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public Address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string zipL {
            get {
                return this.zipLField;
            }
            set {
                this.zipLField = value;
            }
        }
        
        /// <remarks/>
        public string zipR {
            get {
                return this.zipRField;
            }
            set {
                this.zipRField = value;
            }
        }
        
        /// <remarks/>
        public bool carAccess {
            get {
                return this.carAccessField;
            }
            set {
                this.carAccessField = value;
            }
        }
        
        /// <remarks/>
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class Address {
        
        private string streetField;
        
        private string houseNumberField;
        
        private string zipField;
        
        private string districtField;
        
        private City cityField;
        
        private string zoneField;
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string houseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class AddressInfo {
        
        private int recordCountField;
        
        private int pageCountField;
        
        private AddressLocation[] addressLocationField;
        
        /// <remarks/>
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AddressLocation[] addressLocation {
            get {
                return this.addressLocationField;
            }
            set {
                this.addressLocationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class AddressOptions {
        
        private bool usePhoneticField;
        
        private int searchTypeField;
        
        private ResultRange resultRangeField;
        
        /// <remarks/>
        public bool usePhonetic {
            get {
                return this.usePhoneticField;
            }
            set {
                this.usePhoneticField = value;
            }
        }
        
        /// <remarks/>
        public int searchType {
            get {
                return this.searchTypeField;
            }
            set {
                this.searchTypeField = value;
            }
        }
        
        /// <remarks/>
        public ResultRange resultRange {
            get {
                return this.resultRangeField;
            }
            set {
                this.resultRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class ResultRange {
        
        private int pageIndexField;
        
        private int recordsPerPageField;
        
        /// <remarks/>
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        public int recordsPerPage {
            get {
                return this.recordsPerPageField;
            }
            set {
                this.recordsPerPageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class POILocation {
        
        private string nameField;
        
        private string districtField;
        
        private bool carAccessField;
        
        private string dataSourceField;
        
        private City cityField;
        
        private Point pointField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        public bool carAccess {
            get {
                return this.carAccessField;
            }
            set {
                this.carAccessField = value;
            }
        }
        
        /// <remarks/>
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        public City city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public Point point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.maplink2.com.br")]
    public partial class POIInfo {
        
        private int recordCountField;
        
        private int pageCountField;
        
        private POILocation[] poiLocationsField;
        
        /// <remarks/>
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public POILocation[] poiLocations {
            get {
                return this.poiLocationsField;
            }
            set {
                this.poiLocationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void findPOICompletedEventHandler(object sender, findPOICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findPOICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findPOICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public POIInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((POIInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void findAddressCompletedEventHandler(object sender, findAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void findRoadCompletedEventHandler(object sender, findRoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findRoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findRoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RoadInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RoadInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void findDistrictCompletedEventHandler(object sender, findDistrictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findDistrictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findDistrictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DistrictInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DistrictInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAddressCompletedEventHandler(object sender, getAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressLocation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressLocation)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getXYCompletedEventHandler(object sender, getXYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Point Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Point)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getRoadXYCompletedEventHandler(object sender, getRoadXYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRoadXYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRoadXYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Point Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Point)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getXYRadiusWithMapCompletedEventHandler(object sender, getXYRadiusWithMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXYRadiusWithMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXYRadiusWithMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MapInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MapInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void findCityCompletedEventHandler(object sender, findCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CityLocationInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CityLocationInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591